### PR TITLE
accept pr or die

### PR DESCRIPTION
**Pull request by bluestar-b**

### CODE REVIEW

**Review by blueskychan-dev — COMMENTED** [review]
[REMOVED]

**Comment by blueskychan-dev** [comment]
Don't worry, he can nevermind this pr and he will still alive because he didn't close or deny it.

**Comment by bluestar-b** [comment]
fuck off

**Comment by bluestar-b** [comment]
delete your fucking comment and kill yourself now

**Comment by blueskychan-dev** [comment]
We should have new branch for other languages or new repo, maybe.

**Comment by bluestar-b** [comment]
shut the fuck up

**Comment by bluestar-b** [comment]
i said delete your fucking comment and get off

**Comment by blueskychan-dev** [comment]
I'm done.

**Comment by bluestar-b** [comment]
done what i said delete it fuck you

**Comment by blueskychan-dev** [comment]
> done what i said delete it fuck you 

The PR comment **should** be nice, not hate speech to ask ppl to delete things, i scared you to broke the GitHub tos, so.

**Comment by bluestar-b** [comment]
i said delete and you didn't? what next? kill yourself?

**Comment by bluestar-b** [comment]
then just kill yourself now

**Comment by blueskychan-dev** [comment]
> then just kill yourself now

Well?

**Comment by bluestar-b** [comment]
how many times do you want stupid creature

**Comment by bluestar-b** [comment]
i said delete and it's fucking easy are you fucking idiot fucker that can't even click a fucking button?

**Comment by blueskychan-dev** [comment]
> i said delete and it's fucking easy are you fucking idiot fucker that can't even click a fucking button?

ugh, I'm done, since it's is not ur repo (even it's is ur pr) i will delete because it's will bomb up my mailbox, keep in the mind, I don't know did anything will happen after this or not.

**Comment by blueskychan-dev** [comment]
I'm done, can't remove.

**Comment by bluestar-b** [comment]
u fucking retarded github browser exists are you fucking stupid

**Comment by bluestar-b** [comment]
imagine just putting removed label 
you're totally retarded

**Comment by KaityXD** [comment]
stop commenting my project bruh

**Comment by bluestar-b** [comment]
> stop commenting my project bruh

no and never until it completely deleted

**Comment by blueskychan-dev** [comment]
> imagine just putting removed label you're totally retarded [REMOVED]🤓 [REMOVED, REQUEST BY BLUESTAR-B] real nerd🤓

Screenshot_20240909_111018_Chrome

**Comment by bluestar-b** [comment]
> > imagine just putting removed label you're totally retarded [REMOVED]🤓 [REMOVED, REQUEST BY BLUESTAR-B] real nerd🤓
> 
> Screenshot_20240909_111018_Chrome

Screenshot_20240909-111128
shut the fuck up retarded

**Comment by bluestar-b** [comment]
> [REMOVED]

and this?

**Comment by blueskychan-dev** [comment]
> > [REMOVED]
> 
> and this?

I already sent screenshot, it's can't remove and impossible to remove.

People it's can do it is "kat"

**Comment by bluestar-b** [comment]
fuck you i said 

> > > [REMOVED]
> > 
> > 
> > and this?
> 
> I already sent screenshot, it's can't remove and impossible to remove.
> 
> People it's can do it is "kat"

fuck you I said use github browser are you fucking idiot?

**Comment by blueskychan-dev** [comment]
> fuck you i said 
> 
> > > > [REMOVED]
> > > 
> > > 
> > > and this?
> > 
> > I already sent screenshot, it's can't remove and impossible to remove.
> > 
> > People it's can do it is "kat"
> 
> fuck you I said use github browser are you fucking idiot?

I SAID, I ALREADY CHECK ON BROWSER

**Comment by bluestar-b** [comment]
> > fuck you i said
> > > > > [REMOVED]
> > > > 
> > > > 
> > > > and this?
> > > 
> > > 
> > > I already sent screenshot, it's can't remove and impossible to remove.
> > > People it's can do it is "kat"
> > 
> > 
> > fuck you I said use github browser are you fucking idiot?
> 
> I SAID, I ALREADY CHECK ON BROWSER
mobile mode🤓👆

**Comment by blueskychan-dev** [comment]
> > > fuck you i said
> > > > > > [REMOVED]
> > > > > 
> > > > > 
> > > > > and this?
> > > > 
> > > > 
> > > > I already sent screenshot, it's can't remove and impossible to remove.
> > > > People it's can do it is "kat"
> > > 
> > > 
> > > fuck you I said use github browser are you fucking idiot?
> > 
> > I SAID, I ALREADY CHECK ON BROWSER
> mobile mode🤓👆

**Comment by bluestar-b** [comment]
wht fuck i mean disable the fucking desktop mode

**Comment by blueskychan-dev** [comment]
> the fuck i mean disable the fucking desktop mode 

Same results:

**Comment by bluestar-b** [comment]
skill issues 

> > the fuck i mean disable the fucking desktop mode
> 
> Same results:

skill issues

**Comment by bluestar-b** [comment]
Screenshot_20240909-113847
🤓

**Comment by blueskychan-dev** [comment]
> Screenshot_20240909-113847
> 🤓

I can delete my comment unless the first comment that i reviewed, it's impossible.

It's done, I'm sorry, please kill me... I gonna cry. 🥲

**Pull request closed without merging**
